
services:
  app:
    build: .
    container_name: onlinegarden-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://diplomproject.cloiwa66sqiw.eu-north-1.rds.amazonaws.com:3306/onlinegardenshop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: DeyanSpasovBerlin


