version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-local
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onlineGardenShop_prod
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: onlinegarden-app-local
    ports:
      - "8080:8080"
    environment:
#      docker
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
#      ${MYSQL_PASSWORD}
    depends_on:
      - db

volumes:
  db_data:
