version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: onlinegarden-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: onlineGardenShop
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - onlinegarden-network

  app:
    build: .
    container_name: onlinegarden-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/onlineGardenShop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - onlinegarden-network

volumes:
  mysql-data:

networks:
  onlinegarden-network:
    driver: bridge