-- MySQL Script generated by MySQL Workbench
-- Fri Feb 28 08:57:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema onlineGardenShop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema onlineGardenShop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `onlineGardenShop` DEFAULT CHARACTER SET utf8 ;
USE `onlineGardenShop` ;

-- -----------------------------------------------------
-- Table `onlineGardenShop`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineGardenShop`.`users` ;

CREATE TABLE IF NOT EXISTS `onlineGardenShop`.`users` (
  `id` INT NOT NULL,
  `last_name` VARCHAR(150) NULL,
  `first_name` VARCHAR(150) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `password` VARCHAR(100) NULL,
  `role` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlineGardenShop`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineGardenShop`.`cart` ;

CREATE TABLE IF NOT EXISTS `onlineGardenShop`.`cart` (
  `id` INT NOT NULL,
  `users_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_cart_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `onlineGardenShop`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlineGardenShop`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineGardenShop`.`categories` ;

CREATE TABLE IF NOT EXISTS `onlineGardenShop`.`categories` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlineGardenShop`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineGardenShop`.`products` ;

CREATE TABLE IF NOT EXISTS `onlineGardenShop`.`products` (
  `id` INT NOT NULL,
  `name` VARCHAR(150) NULL,
  `categories_id` INT NULL,
  `description` VARCHAR(250) NULL,
  `price` float(53) NULL,
  `discount_price` float(53) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `image_url` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_products_categories1_idx` (`categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `onlineGardenShop`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlineGardenShop`.`FAVORITES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineGardenShop`.`FAVORITES` ;

CREATE TABLE IF NOT EXISTS `onlineGardenShop`.`FAVORITES` (
  `id` INT NOT NULL,
  `users_id` INT NULL,
  `products_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_FAVORITES_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_favorites_products_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_FAVORITES_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `onlineGardenShop`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorites_products`
    FOREIGN KEY (`products_id`)
    REFERENCES `onlineGardenShop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlineGardenShop`.`cart_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineGardenShop`.`cart_items` ;

CREATE TABLE IF NOT EXISTS `onlineGardenShop`.`cart_items` (
  `id` INT NOT NULL,
  `quantity` INT NULL,
  `cart_id` INT NULL,
  `products_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_cart_items_cart1_idx` (`cart_id` ASC) VISIBLE,
  INDEX `fk_cart_items_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_items_cart1`
    FOREIGN KEY (`cart_id`)
    REFERENCES `onlineGardenShop`.`cart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_items_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `onlineGardenShop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlineGardenShop`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineGardenShop`.`orders` ;

CREATE TABLE IF NOT EXISTS `onlineGardenShop`.`orders` (
  `id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delivery_address` VARCHAR(150) NULL,
  `contact_phone` VARCHAR(60) NULL,
  `delivery_method` VARCHAR(60) NULL,
  `status` VARCHAR(150) NULL,
  `users_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_orders_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `onlineGardenShop`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlineGardenShop`.`order_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineGardenShop`.`order_items` ;

CREATE TABLE IF NOT EXISTS `onlineGardenShop`.`order_items` (
  `id` INT NOT NULL,
  `quantity` INT NULL,
  `purchase_price` DECIMAL(15,2) NULL,
  `orders_id` INT NULL,
  `products_id` INT NULL,
  `price_at_purchase` FLOAT(53),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_order_items_orders1_idx` (`orders_id` ASC) VISIBLE,
  INDEX `fk_order_items_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_items_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `onlineGardenShop`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_items_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `onlineGardenShop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
